### ISSUE TITLE
How to manage year-end transactions when generating an income statement.

### ISSUE THREAD

**Issue by mbucc** [Nick-Triller/accounting#11]
Hi Nick,

I've been working on generating reports with command-line on the feature branch [https://github.com/mbucc/accounting/tree/develop/reports](develop/reports).  My journal spans multiple years, and the current implementation outputs a balance sheet and trial balance for each year-end in the journal.  This is simple, as balance sheet accounts are permanent in that their balances always roll forward.

I'd like to add income statements, but I'm not sure how to handle the year-end closing transactions.

At year-end, you are zero-out all expense and revenue accounts by (hopefully!) crediting equity, crediting expense, and debiting revenue.  (I'm glossing over some details here but you get the idea.)

The best approach I've can think of is to identify this (or these) year-end transactions using a "magic" local time (say, one millisecond before the year-end) and then write the income statement report code to ignore any such year-end transactions.

Do you know of a better way?

**Comment by Nick-Triller** [comment]
Hi Mark,

I am not a fan of the magic timestamp idea. I would prefer an explicit flag in the transaction type.
