### ISSUE TITLE
Roll-up accounts

### ISSUE THREAD

**Issue by mbucc** [Nick-Triller/accounting#12]
For your review and comment:

I'd like to add a RollupAccount type that allows you to print a version of the balance sheet and income statement reports at a higher level of aggregation.

Aggregate Rules
* If an Account is mapped to a RollupAccount, the account is printed as a child account of the rollup.
* If an Account is not mapped to a RollupAccount, the account printed as a top-level account, possibly at the same level as a rollup account.
* All Accounts mapped to the same RollupAccount must have the same (increase-side, is-balance-sheet-account) tuple.

The idea here is to keep reports working by not requiring every Account to have an associated RollupAccount.

I think I can make this work with just new row types in the import TSV file:
`ROLLUP_ACCOUNT<tab>name<tab>one or more comma-delimited AccountNumbers`

**Comment by Nick-Triller** [comment]
Hi Mark,
this sounds like a useful addition to me.
