### ISSUE TITLE
Dont understand the point with the AccountingSide parameter to addAccount

### ISSUE THREAD

**Issue by jarlah** [Nick-Triller/accounting#13]
Hi

I have tried to play around a bit, to debug, and I was creating two transactions. Changing the AccountingSide on the account definitions doesn't change anything. Shouldn't it? 

```java
import core.Ledger;
import core.chartofaccounts.ChartOfAccountsBuilder;

import java.math.BigDecimal;

import static core.account.AccountSide.CREDIT;
import static core.account.AccountSide.DEBIT;

public class Main {
    public static void main(String[] args) {
        // Setup ledger
        var coa = ChartOfAccountsBuilder.create()
                .addAccount("1234", "Some debit account 1234", DEBIT)
                //.addAccount("1234", "Some debit account 1234", CREDIT) <- doesn't affect trial balance!
                .addAccount("4321", "Some debit account 4321", CREDIT)
                .addAccount("2344", "Some credit account 2344.", CREDIT)
                .build();

        var ledger = new Ledger(coa);

        var transaction1 = ledger
                .createTransaction(null)
                .debit(new BigDecimal(1125), "1234")
                .credit(new BigDecimal(1125), "4321")
                .build();

        ledger.commitTransaction(transaction1);

        var transaction2 = ledger
                .createTransaction(null)
                .debit(new BigDecimal(375), "1234")
                .credit(new BigDecimal(375), "2344")
                .build();

        ledger.commitTransaction(transaction2);

        // Print ledger
        System.out.println(ledger.toString());

        // Print trial balance
        var trialBalanceResult = ledger.computeTrialBalance();
        System.out.println(trialBalanceResult.toString());
    }
}
```

Why doesn't Account.accountingSide affect trial balance? 

Can you verify that this example actually gives the same output on your machines?

**Comment by jarlah** [comment]
Actually, I suspect that this is the problem:

<img width="855" alt="Screenshot 2021-01-26 at 00 07 31" src="https://user-images.githubusercontent.com/404102/105777338-7e981400-5f6a-11eb-9883-70be5579221a.png">

which should be this:

```java
        BigDecimal balance = accounts.stream()
                .reduce(
                        BigDecimal.ZERO,
                        (acc, next) -> acc.add(next.getBalance()),
                        BigDecimal::add
                );
        isBalanced = balance.equals(BigDecimal.ZERO);
```

and this makes my test fail.... in every scenario . doesn't matter what I say the accountingSide for an account is

**Comment by jarlah** [comment]
And then again the same question arises. What is Account.accountingSide for ? Why do every account used in a transaction has to be either DEBIT or CREDIT? why can't I like make a transaction with **_debit to a credit account_** and **_credit to a debit account_**? Am I missing something here? Where is the tests for different kinds of accounts in the same transaction? And not just DEBIT ? ;) :trollface:

**Comment by jarlah** [comment]
if someone sees this, I decided to not care about it and move on. But if you can explain it, great!

**Comment by Nick-Triller** [comment]
Hi @jarlah,

thanks for the investigation. The balance check in `TrialBalanceResult` was indeed broken in two ways.
The trial balance always reported `isBalanced=true` because of the bug you found. Furthermore,  `increaseSide` shouldn't be considered when calculating `TrialBalanceResult`. It's supposed to be metadata for display purposes. I fixed these issues and changed the example in the README to use accounts with both CREDIT and DEBIT increase side.

That being said, the code in this repository was written in one weekend when I was a student. I wanted to play around with design patterns and never used it in any project. I would advise against using it in any serious context.

Best
Nick
