### ISSUE TITLE
Use lombok

### ISSUE THREAD

**Issue by vphilipnyc** [Nick-Triller/accounting#3]
@Nick-Triller - would you care if we included lombok as a dependency?  This would make beans less verbose and error-prone.  I'd understand completely if you would rather not include another dependency, but I've found it very useful and it's pretty popular in general.

I can add it if you're cool with it.  If not, feel free to close this issue.  Note: I'd add it with `provided` scope.

**Comment by vphilipnyc** [comment]
See https://github.com/Nick-Triller/accounting/pull/4

**Comment by Nick-Triller** [comment]
I am fine with lombok. The PR will be accepted as soon as I have reviewed it. Thx!
